# codemagic.yaml
# For more information about this file, see https://docs.codemagic.io/yaml-basic-configuration/

workflows:
  android-app-build:
    name: Android Release Build
    instance_type: mac_mini_m2
    max_build_duration: 60
    environment:
      flutter: stable
      groups:
        - keystore_credentials # This group should contain your keystore variables
        - supabase_credentials
    scripts:
      - name: Set Java version to 17
        script: |
          sudo xcode-select --switch /Library/Java/JavaVirtualMachines/zulu-17.jdk/Contents/Home
          java -version
      - name: Set up local.properties
        script: echo "flutter.sdk=$FLUTTER_ROOT" > "$CM_BUILD_DIR/android/local.properties"
      - name: Set up Android keystore from custom environment variables
        script: |
          echo "Decoding keystore from MY_KEYSTORE_BASE64..."
          echo $MY_KEYSTORE_BASE64 | base64 --decode > /tmp/keystore.jks
          echo "Creating key.properties file..."
          cat > "$CM_BUILD_DIR/android/key.properties" <<EOF
          storeFile=/tmp/keystore.jks
          storePassword=$MY_STORE_PASSWORD
          keyPassword=$MY_KEY_PASSWORD
          keyAlias=$MY_KEY_ALIAS
          EOF
          echo "key.properties file created successfully."
      - name: Get Flutter packages
        script: flutter packages pub get
      - name: Fix flutter_credit_card namespace issue
        script: |
          sed -i.bak 's/compileSdkVersion 33/namespace "com.github.SimformSolutionsPvtLtd.flutter_credit_card"\n    compileSdkVersion 33/' "$HOME/.pub-cache/hosted/pub.dev/flutter_credit_card-4.0.1/android/build.gradle"
      - name: Replace Supabase credentials
        script: |
          sed -i.bak "s|PLACEHOLDER_SUPABASE_URL|$SUPABASE_URL|g" "lib/main.dart"
          sed -i.bak "s|PLACEHOLDER_SUPABASE_ANON_KEY|$SUPABASE_ANON_KEY|g" "lib/main.dart"
      - name: Build Android release APK
        script: flutter build apk --release
    artifacts:
      - build/app/outputs/flutter-apk/app-release.apk
    publishing:
      email:
        recipients:
          - tips.waiyanhtet@gmail.com
        notify:
          success: true
          failure: true
